"""0001_initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-19 21:17:33.286301

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counterparties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_counterparties_external_id"), "counterparties", ["external_id"], unique=True
    )
    op.create_table(
        "ledger_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ledger_events_created_at"), "ledger_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_ledger_events_entity", "ledger_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "policy_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("fix_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policy_versions_version"), "policy_versions", ["version"], unique=True)
    op.create_table(
        "receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("counterparty_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("original_reference", sa.String(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of", sa.UUID(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_receipts_counterparty_id"), "receipts", ["counterparty_id"], unique=False
    )
    op.create_index(op.f("ix_receipts_reference"), "receipts", ["reference"], unique=False)
    op.create_table(
        "receivables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("counterparty_id", sa.UUID(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("shipping", sa.BigInteger(), nullable=False),
        sa.Column("allocated", sa.BigInteger(), nullable=False),
        sa.Column("adjusted", sa.BigInteger(), nullable=False),
        sa.Column("remaining", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PARTIALLY_PAID", "SETTLED", "CANCELLED", name="receivable_status"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_receivables_counterparty_id"), "receivables", ["counterparty_id"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("batch_label", sa.String(), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clusters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("cause", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_cited", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "kind", sa.Enum("ESCALATED", "ABSORBED", "MIXED", name="cluster_kind"), nullable=False
        ),
        sa.Column("source", sa.Enum("CODE", "CLAUDE", name="cluster_source"), nullable=False),
        sa.Column(
            "status", sa.Enum("OPEN", "FIXED", "DISMISSED", name="cluster_status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column(
            "outcome", sa.Enum("SETTLED", "ESCALATED", name="decision_outcome"), nullable=False
        ),
        sa.Column("rule_id", sa.String(), nullable=True),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("matched_by", sa.String(), nullable=True),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_outcome", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_run_id"), "decisions", ["run_id"], unique=False)
    op.create_table(
        "run_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "unapplied_credits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("counterparty_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HELD", "REFUNDED", "APPLIED", name="unapplied_credit_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("receivable_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receivable_id"],
            ["receivables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exceptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason_code",
            sa.Enum(
                "NO_MATCH",
                "MULTIPLE_CANDIDATES",
                "SHORT_PAY",
                "OVERPAYMENT",
                "PARTIAL_PAYMENT_PENDING",
                "PAYMENT_ON_CANCELLED",
                "DUPLICATE_RECEIPT",
                "SUSPECTED_DUPLICATE",
                "FEE_DEDUCTED",
                "ONE_RECEIPT_MANY_RECEIVABLES",
                name="reason_code",
            ),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "RESOLVED", name="exception_status"), nullable=False),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exceptions_status"), "exceptions", ["status"], unique=False)
    op.create_table(
        "fixes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "F1_ADD_COUNTERPARTY_ALIAS",
                "F2_REPAIR_REFERENCE",
                "F3_MARK_DUPLICATE",
                "F4_SPLIT_RECEIPT",
                "F5_RECORD_FEE_DEDUCTION",
                "F6_AMEND_POLICY",
                "F7_MANUAL_REVIEW",
                name="fix_type",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_widening", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "DRY_RUN",
                "APPROVED",
                "APPLIED",
                "REJECTED",
                "VERIFICATION_FAILED",
                "REVERTED",
                name="fix_status",
            ),
            nullable=False,
        ),
        sa.Column("inverse", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # deferred: policy_versions.fix_id -> fixes.id, added via ALTER once both tables exist,
    # to break the runs -> clusters -> fixes -> policy_versions -> runs FK cycle.
    op.create_foreign_key(
        "fk_policy_versions_fix_id", "policy_versions", "fixes", ["fix_id"], ["id"]
    )
    op.create_table(
        "adjustments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receivable_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum("ROUNDING", "SHORT_PAY", "TOLERANCE", "FEE", name="adjustment_reason"),
            nullable=False,
        ),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("fix_id", sa.UUID(), nullable=True),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receivable_id"],
            ["receivables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fix_id", sa.UUID(), nullable=False),
        sa.Column("fix_version", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("REVIEWER", "APPROVER", name="approval_role"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "decision", sa.Enum("APPROVE", "REJECT", name="approval_decision"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("snapshot_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "condition_signatures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fix_id", sa.UUID(), nullable=False),
        sa.Column("predicate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "counterparty_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_id", sa.UUID(), nullable=False),
        sa.Column("alias_external_id", sa.String(), nullable=False),
        sa.Column("alias_name", sa.String(), nullable=False),
        sa.Column("fix_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_counterparty_aliases_alias_external_id"),
        "counterparty_aliases",
        ["alias_external_id"],
        unique=False,
    )
    op.create_table(
        "dry_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fix_id", sa.UUID(), nullable=False),
        sa.Column("fix_version", sa.Integer(), nullable=False),
        sa.Column("predicted_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("side_effects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fix_id", sa.UUID(), nullable=False),
        sa.Column("prediction_matched", sa.Boolean(), nullable=False),
        sa.Column("invariants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum("VERIFIED", "VERIFICATION_FAILED", name="verification_outcome"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fix_id"],
            ["fixes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cluster_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("exception_id", sa.UUID(), nullable=True),
        sa.Column("adjustment_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["adjustments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cluster_members_cluster_id"), "cluster_members", ["cluster_id"], unique=False
    )
    op.create_table(
        "recurrence_samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signature_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("appeared", sa.Integer(), nullable=False),
        sa.Column("auto_handled", sa.Integer(), nullable=False),
        sa.Column("needed_human", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_id"],
            ["condition_signatures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurrence_samples")
    op.drop_index(op.f("ix_cluster_members_cluster_id"), table_name="cluster_members")
    op.drop_table("cluster_members")
    op.drop_table("verifications")
    op.drop_table("dry_runs")
    op.drop_index(
        op.f("ix_counterparty_aliases_alias_external_id"), table_name="counterparty_aliases"
    )
    op.drop_table("counterparty_aliases")
    op.drop_table("condition_signatures")
    op.drop_table("approvals")
    op.drop_table("adjustments")
    op.drop_constraint("fk_policy_versions_fix_id", "policy_versions", type_="foreignkey")
    op.drop_table("fixes")
    op.drop_index(op.f("ix_exceptions_status"), table_name="exceptions")
    op.drop_table("exceptions")
    op.drop_table("allocations")
    op.drop_table("unapplied_credits")
    op.drop_table("run_reports")
    op.drop_index(op.f("ix_decisions_run_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_table("clusters")
    op.drop_table("runs")
    op.drop_index(op.f("ix_receivables_counterparty_id"), table_name="receivables")
    op.drop_table("receivables")
    op.drop_index(op.f("ix_receipts_reference"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_counterparty_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_policy_versions_version"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index("ix_ledger_events_entity", table_name="ledger_events")
    op.drop_index(op.f("ix_ledger_events_created_at"), table_name="ledger_events")
    op.drop_table("ledger_events")
    op.drop_index(op.f("ix_counterparties_external_id"), table_name="counterparties")
    op.drop_table("counterparties")
    # ### end Alembic commands ###

    # autogenerate creates enum types inline with the first column that uses them, but
    # doesn't drop them when the table goes away -- drop explicitly so downgrade is clean.
    for enum_name in (
        "receivable_status",
        "adjustment_reason",
        "unapplied_credit_status",
        "decision_outcome",
        "reason_code",
        "exception_status",
        "cluster_kind",
        "cluster_source",
        "cluster_status",
        "fix_type",
        "fix_status",
        "approval_role",
        "approval_decision",
        "verification_outcome",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
